.TH "Signal" 3 "Sat Nov 14 2020" "Lab 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Signal \- An Implementation of a Rendezvous using Semaphores\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
An Implementation of a Rendezvous using Semaphores\&. 

Utilizes C++11 features, for example, mutex and condition variables to implement an example of a rendezvous for threads : C00226131, Aaron Finlay 

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 3 from the source code\&.
